# Generated by Django 5.2.7 on 2025-10-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_product_sale_saleitem_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('gm', 'Gram'), ('lt', 'Liter'), ('ml', 'Milliliter'), ('piece', 'Piece'), ('packet', 'Packet'), ('box', 'Box'), ('dozen', 'Dozen')], default='piece', max_length=20),
        ),
    ]
