# Generated by Django 5.2.7 on 2025-11-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_product_stock_quantity_alter_saleitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogram'), ('gm', 'Gram'), ('lt', 'Liter'), ('ml', 'Milliliter'), ('piece', 'Piece'), ('packet', 'Packet'), ('box', 'Box'), ('dozen', 'Dozen')], default='piece', max_length=20),
        ),
    ]
