# Generated by Django 5.2.7 on 2025-11-01 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_product_product_type_alter_product_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('offer_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount'), ('bogo', 'Buy One Get One Free'), ('combo', 'Combo Offer'), ('free_item', 'Free Item with Purchase')], max_length=20)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition_type', models.CharField(choices=[('bill_amount', 'Minimum Bill Amount'), ('product', 'Specific Products'), ('category', 'Product Category'), ('festival', 'Festival/Special Day')], max_length=20)),
                ('min_bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('applicable_categories', models.JSONField(blank=True, default=list)),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='offers', to='customers.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_offers', to='customers.offer')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_offers', to='customers.sale')),
            ],
            options={
                'verbose_name': 'Sale Offer',
                'verbose_name_plural': 'Sale Offers',
            },
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['user', '-start_date'], name='customers_o_user_id_876aed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saleoffer',
            unique_together={('sale', 'offer')},
        ),
    ]
