# Generated by Django 5.2.7 on 2025-11-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_offer_saleoffer_offer_customers_o_user_id_876aed_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='offer',
            name='customers_o_user_id_876aed_idx',
        ),
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='saleoffer',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['user', '-created_at'], name='customers_o_user_id_543ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='customers_o_is_acti_faf882_idx'),
        ),
        migrations.AddIndex(
            model_name='saleoffer',
            index=models.Index(fields=['sale'], name='customers_s_sale_id_42d6b6_idx'),
        ),
        migrations.AddIndex(
            model_name='saleoffer',
            index=models.Index(fields=['offer'], name='customers_s_offer_i_b6205c_idx'),
        ),
    ]
