# Generated by Django 5.2.7 on 2026-01-10 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_remove_offer_customers_o_user_id_876aed_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='saleoffer',
            options={'verbose_name_plural': 'Sale Offers'},
        ),
        migrations.RemoveIndex(
            model_name='offer',
            name='customers_o_user_id_543ba2_idx',
        ),
        migrations.RemoveIndex(
            model_name='offer',
            name='customers_o_is_acti_faf882_idx',
        ),
        migrations.RemoveIndex(
            model_name='saleoffer',
            name='customers_s_sale_id_42d6b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='saleoffer',
            name='customers_s_offer_i_b6205c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='saleoffer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='offer',
            name='applicable_categories',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='condition_type',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_bill_amount',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='title',
        ),
        migrations.AddField(
            model_name='offer',
            name='buy_quantity',
            field=models.IntegerField(default=0, help_text='Buy X items'),
        ),
        migrations.AddField(
            model_name='offer',
            name='get_quantity',
            field=models.IntegerField(default=0, help_text='Get Y items free'),
        ),
        migrations.AddField(
            model_name='offer',
            name='min_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='name',
            field=models.CharField(default='New Offer', max_length=255),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('flat', 'Flat Discount'), ('percentage', 'Percentage Discount'), ('bogo', 'Buy X Get Y')], default='flat', max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='saleoffer',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['user', 'start_date', 'end_date'], name='customers_o_user_id_3fbdcd_idx'),
        ),
        migrations.RemoveField(
            model_name='saleoffer',
            name='created_at',
        ),
    ]
