# Generated by Django 5.2.7 on 2026-01-16 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_profile_remove_userprofile_user_alter_offer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='applicable_products',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_purchase_amount',
        ),
        migrations.AlterField(
            model_name='shopphoto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
