# Generated by Django 5.2.7 on 2026-01-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_remove_offer_applicable_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, related_name='offers', to='customers.product'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='min_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
