# Generated by Django 5.2.7 on 2026-01-16 18:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_offer_applicable_products_offer_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, default='My Shop', max_length=255)),
                ('shop_category', models.CharField(choices=[('pizza', 'Pizza/Fast Food'), ('clothes', 'Clothes'), ('grocery', 'Grocery'), ('bartan', 'Bartan/Utensils'), ('medical', 'Medical'), ('electronics', 'Electronics'), ('other', 'Other')], default='other', max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('shop_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='saleoffer',
            options={'verbose_name_plural': 'Sale Offers'},
        ),
        migrations.AlterModelOptions(
            name='shopphoto',
            options={'ordering': ['display_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='product', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogram'), ('gm', 'Gram'), ('lt', 'Liter'), ('ml', 'Milliliter'), ('piece', 'Piece'), ('packet', 'Packet'), ('box', 'Box'), ('dozen', 'Dozen')], default='piece', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='buy_quantity',
            field=models.IntegerField(default=0, help_text='Buy X items'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offer',
            name='get_quantity',
            field=models.IntegerField(default=0, help_text='Get Y items free'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(default='New Offer', max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('flat', 'Flat Discount'), ('percentage', 'Percentage Discount'), ('bogo', 'Buy X Get Y')], default='flat', max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('pizza', 'Pizza/Fast Food'), ('clothes', 'Clothes'), ('grocery', 'Grocery'), ('bartan', 'Bartan/Utensils'), ('medical', 'Medical'), ('electronics', 'Electronics'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='customers.product'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleoffer',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleoffer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_offers', to='customers.offer'),
        ),
        migrations.AlterField(
            model_name='saleoffer',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_offers', to='customers.sale'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user', '-created_at'], name='customers_c_user_id_b16f30_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['user', 'start_date', 'end_date'], name='customers_o_user_id_3fbdcd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'category'], name='customers_p_user_id_b1c263_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['user', '-sale_date'], name='customers_s_user_id_376a4b_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
