# Generated by Django 5.2.7 on 2026-01-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_userprofile_remove_profile_user_alter_offer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'हिंदी')], default='en', help_text='Preferred language for the application interface', max_length=10),
        ),
    ]
