# Generated by Django 5.2.7 on 2026-01-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_userprofile_preferred_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_language',
        ),
        migrations.AddField(
            model_name='customuser',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_pending_deletion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
