# Generated by Django 5.2.7 on 2026-02-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_useractivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='udhar_amount',
            new_name='credit_amount',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='added_to_udhar',
            new_name='added_to_credit',
        ),
    ]
