# Generated by Django 5.2.7 on 2026-02-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_rename_udhar_amount_customer_credit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
